name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      HOST: machine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses:  actions-rust-lang/setup-rust-toolchain@v1
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run Tests
        run: cargo test --all-targets --all-features
